# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += rzboard-hdmi.dtbo
dtb-y += rzboard-ov5640.dtbo
dtb-y += rzboard-cm33.dtbo
dtb-y += rzboard-can.dtbo
dtb-y += rzboard-adc.dtbo
dtb-y += rzboard-lite-audio.dtbo
dtb-y += rzboard-ext-uart2.dtbo
dtb-y += rzboard-ext-i2c.dtbo
dtb-y += rzboard-ext-spi.dtbo
dtb-y += rzboard-mipi.dtbo
